djangoproject1/books/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings

app_name = 'books'


urlpatterns = [

    url(r'^$', views.books_list, name='book_list'),
    url(r'^search/$', views.search, name='search'),
    url(r'^login/$', views.userlogin, name='user_login'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^login/$', views.login, name='login'),
    url(r'^add_book/$', views.add_book, name='add_book'),
    url(r'^detail/(?P<id>\d+)/$', views.book_detail, name='detail'),
    url(r'^like/(?P<book_id>\d+)/$', views.like_this_book, name ='like_this_book'),
    url(r'^update_book/(?P<book_id>\d+)/$', views.update_book, name='update_book'),
    url(r'^delete_book/(?P<book_id>\d+)/$', views.conform_delete, name='conform_delete'),
    url(r'register/$', views.register, name='register'),


]



#if settings.DEBUG:
#  urlpatterns +=[url(r'^debuginfo/$', views.debug),]

djangoproject1/ican/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^notification/', include('notification.urls', namespace="Notification")),
    url(r'^books/', include('books.urls', namespace="books")),
    url(r'^polls/', include('polls.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

djangoproject1/books/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
#from django.core.urlresolvers import reverse
from django.urls import reverse

class UserProfile(models.Model):

    user = models.OneToOneField(User,on_delete = models.CASCADE)
    bio = models.TextField(default='here is my bio')
    picture = models.ImageField(upload_to = 'users_prof_img/%Y/%m/%d', blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_profile(sender, **kwargs):
    if kwargs.get('created', False):
        UserProfile.objects.get_or_create(user=kwargs.get('instance'))




class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length = 60)
    stat_province = models.CharField(max_length = 30)
    country = models.CharField(max_length=50)
    web_site = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    sex = models.CharField(max_length=1, choices=(('M','male'),('F','female')),default='F')
    email = models.EmailField(blank=True, verbose_name='e-mail')
    def __str__(self):
        return u'%s %s' %(self.first_name, self.last_name)


class Book(models.Model):
    title = models.CharField(max_length=50)
    descrp = models.TextField(null=True, blank=True)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher,on_delete = models.CASCADE)
    publicatin_date = models.DateField(blank=True, null=True)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


    def get_absolute_url(self):

        return reverse("books:detail", kwargs={"id": self.id})
        # documentation return reverse('books.views.book_detail', args=[str(self.id)])


class likes(models.Model):
    likes_num = models.IntegerField(default=0)
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    book = models.ForeignKey(Book,on_delete = models.CASCADE)
    liked_on = models.DateTimeField(auto_now_add=True)

djangoproject1/books/forms.py
from django import forms
from django.contrib.auth.models import User
from books.models import Book
 
# using my_date_formats = ['%d/%m/%Y',] we can ocerride the default input format provided by django

MY_DATE_FORMATS = ['%d/%m/%Y',]


class bookForm(forms.ModelForm):
    publicatin_date = forms.DateField(input_formats=MY_DATE_FORMATS)

    class Meta:
        model = Book
        fields = ('title','descrp', 'authors', 'publisher', 'publicatin_date',)
        

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Email Address')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words ")
        return message


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

djangoproject1/books/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from .models import Book, Author, likes
from django.contrib.auth import authenticate, login 
from django.shortcuts import redirect
from django.http import HttpResponseRedirect, HttpResponse
from books.forms import ContactForm, bookForm
from django.core.mail import send_mail
from django.template import RequestContext
from django.contrib import messages
from django.conf import settings
from .forms import UserForm
from django.contrib.auth.models import User
from django.db.models import F
import datetime
from django.utils import timezone
from django.db.models import Count



def userlogin(request):

    errors = []

    if request.method=='POST':
        

        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return  HttpResponseRedirect('/books/')
            else:
                errors.append(" Sorry your acount is disapled")
                return render(request, 'books/login.html', {'errors': errors})
        else:
            errors.append("invalid login details")
            return render(request, 'books/login.html', {'errors': errors})
    else:
        return render(request, 'books/login.html', {'errors': errors})




def books_list(request):
    
    message = "No Books Yet To Display"
    number_of_likes = 0
    books_list = Book.objects.order_by('-publicatin_date')[:5]
    for bok in books_list:
        number_of_likes = Book.objects.prefetch_related('likes').count()
        #login_count = User.objects.filter(last_login__startswith=timezone.now().date()).count()# in this line i count number of users who logged in tody and i can then just passed it to the dic
        return render(request, 'books/index.html', {'books_list': books_list, 'number_of_likes':number_of_likes,})
    return render_to_response("books/index.html",{"message":message}, context_instance = RequestContext(request))


def book_detail(request, id):

    number_of_likes = 0
    book = get_object_or_404(Book, pk=id)
    b_auth = book.authors.all()
    number_of_likes = book.likes_set.all().count()  
    book.views = book.views + 1
    book.save()
   
    return render(request, 'books/book_detail.html', {'book':book,'number_of_likes':number_of_likes,'b_auth':b_auth})


def like_this_book(request, book_id):
    
    new_like, created = likes.objects.get_or_create(user=request.user, book_id=book_id)

    if not created: #user already liked this boook
        messages.add_message(request, messages.SUCCESS, 'YOU HAVE already liked this book')
        return HttpResponseRedirect('/books')
        
    else:
       # if request.method == 'GET':
          #  book_id = request.GET['book_id']   
        
       
        messages.add_message(request, messages.SUCCESS, 'YOU HAVE SUCCESSFULY liked this book')
        return HttpResponseRedirect('/books')



def add_book(request):
    if request.method == 'POST':
        form = bookForm(request.POST)
        if form.is_valid:
            form.save(commit=True)
            messages.add_message(request , messages.SUCCESS,'YOU HVE SSUCCESSFULY ADD A BOOK')
            
            return redirect('/books')
        else:
            print form.errors
    else:
        form = bookForm()

    return render(request,'books/add_book.html',{'form':form})

def update_book(request, book_id):

    updated_book = get_object_or_404(Book, id=book_id)
    form = bookForm(request.POST or None , instance = updated_book) 
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return redirect('/books')

    context = {
        'title':updated_book.title, 
        'authors':updated_book.authors,
        'publisher':updated_book.publisher,
        'publicatin_date':updated_book.publicatin_date,
        'form':form,
        }
    messages.add_message(request, messages.SUCCESS, 'YOU HAVE UPDATED THE BOOK INF SUCCESSFULY')
    return render(request,'books/add_book.html',context)


def conform_delete(request, book_id):
    obj = get_object_or_404(Book, id=book_id)
    number_of_likes = obj.likes_set.all().count() 
    if request.method =="POST":
        obj.delete()
        messages.add_message(request, settings.DELETE_MESSAGE, "YOU HAVE DELETED THIS BOOK")
        return HttpResponseRedirect('/books/')
    context = {
    "object": obj ,
    "number_of_likes":number_of_likes,
    }
    return render(request, "books/delete_conform.html", context)



def search(request):

    errors = []
    
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            errors.append("please type something to search for")
        elif len(q) > 11:
            errors.append("you can't search for more than 10 charcaters")
        else:
            books = Book.objects.filter(title__icontains=q)
            return render(request, 'books/search_results.html', 
                {'books':books, 'query': q})
    return render(request, 'books/search_form.html',
        {'errors': errors,})

def like_this_book(request, book_id):

    new_like, created = likes.objects.get_or_create(user=request.user, book_id=book_id)
    if not created:
        messages.add_message(request, messages.SUCCESS, 'YOU HAVE already liked this book')
        return HttpResponseRedirect('/books')
        
    else:
        # here we should let the user like this book and register that
        messages.add_message(request, messages.SUCCESS, 'YOU HAVE SUCCESSFULY liked this book')
        return HttpResponseRedirect('/books')
    '''
    this is a view to count num of likes but it is not yet finsh
    book_id = None
    if request.method == 'GET':
        book_id = request.GET['book_id']
    likes = 0
    if book_id:
        book = get_object_or_404(Book, id=int(book_id))
        if book:
            likes = book.likes + 1
            book.likes = likes
            book.save()
            return HttpResponseRedirect('/books')
'''

def contact(request):
    if request.method =='POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'someEmail@gmail.com'),
                ['siteowner@external.com']
            #    cd.get('email', <a class="reference external" href="mailto:'noreplay%40examble.com">'noreply@example.com</a>'),
             #   [<a class="reference external"href="mailto:'siteowner%40examble.com">'siteowner@examble.com</a>'],
            )
            return HttpResponseRedirect('/contact/thanks/')

    else:
        form = ContactForm(
            initial={'subject': 'I love you'}

         )
    return render(request, 'books/contact_form.html', {'form': form,'ip_add':request.META['REMOTE_ADDR']})



def register(request):

    # a boolean value telling the template that the registration was successful
   # set to false initailly. code changes value to true whenregistration succeeds . 

    #if request.session.test_cookie_worked():
      #  print " >>>> TEST COOKIE WORKED "
        

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        


        #if user_form.is_valid() and profile_form.is_valid():

        user = user_form.save()

        # Now we hash the password with the set_password method . 
        # once hashed  we can update the user object

        user.set_password(user.password)

        user.save()

            # Now sort out the userprofile instance
            # once hashed , we can update the user object

            # this delay saving the model until we are ready to avoid integrity problems.


           
           
            #did the user provides a profile picture?
           #if so , we need to set the user attribute ourselves, we set commit =False.
         
           

        return HttpResponseRedirect('/books/')


        registered = True

     


    else:
        user_form = UserForm()
       

    return render(request, 'books/register.html', {'user_form': user_form,'registered': registered })


def login(request):
    if request.method == 'POST':
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()
            return HttpResponse(" you are logged in ")
        else:
            return HttpResponse("please login now ")
    request.session.set_test_cookie()
    return render(request, 'books/login.html')
    '''
    user_id = int(request.POST['id'])
    member = User.objects.get(id=user_id);
    if member.password == request.POST['password']:
        request.session['user_id'] = member.id
        returnHttpResponse("you are in ")
    else:
        return returnHttpResponse(" your username or password is incorrect")

   

'''









                    
   

djangoproject1/books/templates/books/add_book.html
<! DOCTYPE html>

<html>
    <head>
    	<title>add a book</title>
    </head>
    <body>
    	<h1>here you can add a new book</h1>
    <form id="add_book_form" method='post' action='.'>
    	{% csrf_token %}
    	{{ form.as_p }}
    <input type="submit" name="submit" value="Save" />
</form>
</body>
</html>

djangoproject1/books/templates/books/book_detail.html
<h1>{{ book.title }}</h1>

<h4>Written By : {{ book.authors }}</h4>
<h4>published By :{{ book.publisher }}</h4>

<h4> on : {{ book.publicatin_date }}</h4>

<h4> It Was Liked ({{ number_of_likes }}) times.</h4>
	
	<h3>viewed : ({{ book.views}}) times <h3>

djangoproject1/books/templates/books/contact_form.html
<html>
    <head>
        <title>Contact us</title>
    </head>
    <body>
        <h1>Contact us </h1>
    {{ip_add}}

        {% if form.errors %}
            <p style="color: red;">
                  please correct the error{{form.errors|pluralize}} below.
            </p>
        {% endif %}

        <form action="" method="post">
            <table>
                {{ form.as_table }}
            </table>
            {% csrf_token %}
            <input type="submit" value="submit">
        </form>
        </body>
        </html>

<!--   {% if form.errors %}
    <p style="color: red;">
        Please correct the error{{ form.errors|pluralize }} below .
    </p>


{% endif %}
{% csrf_token %}
<form action="" method="post">
    <div class="field">
        {{ form.subject.errors }}
        <label for="id_subject">Subject:</label>
        {{ form.subject }}
    </div>
    <div class="field">
        {{ form.email.errors }}
        <label for="id_email">Email:</label>
         {{ form.email }}
    </div>
    <div class="field">
        {{ form.message.errors }} 
        <label for="id_message">Message:</label>
         {{ form.message }}
    </div>

    <input type="Submit" value="submit"> -->

djangoproject1/books/templates/books/delete_conform.html
<title>Delete Comformation</title>
<h1>Are you sure you want to delete this Book ?</h1>

<h1>{{ object.title }}</h1>


<h3>Published By :{{ object.publisher }}</h3>

<h3> on : {{ object.publicatin_date }}</h3>

<h3> It Was Liked {{ number_of_likes }} times.</h3>
	<form method="POST" action=".">{% csrf_token %}

	<h3>({{ object.views}})views<h3>
	<input type='submit' value='Conform' class='btn btn-warning'>

    <a href="{{ object.get_absolute_url }}">Cancel</a>
</form>

djangoproject1/books/templates/books/index.html
{% load static %}
<!DOCTYPE html>

<html lang="en">


    <head>
        <meta charset="utf-8">
        <title>BOOKS</title>
        <link rel="stylesheet" type="text/css" href="{% static 'books/style.css' %}" />
    </head>

    <body>

        <header class="container group">
            <div class="mymessages">
                {% if messages %}
            <ul class"messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif  %}>{{ message }}</li>
        
                 {% endfor %}
                 {% endif %}
            </ul>
            </div>
            <h1 class="logo">Follow<br> Up Application</h1>
                <h3>August 31&ndash;26th &mdash; Qatar, Doha</h3>
            <nav>
                <a href="">Home</a>
                <a href="">contact us</a>
                <a href="">Promotion</a>
                <a href="">Activty</a>
                <a href="">Donate</a>
                
            </nav>
        </header>


        <section class="hero container"> 
            <h2>Dedicated to the creaft of building websites</h2>
            <p>Every year the world is moving very fast to new consept of development Every year the world is moving very fast to new consept of development Every year the world is moving very fast to new consept of development Every year the world is moving very fast to new consept of development</p>

        <a class="btn btn-alt" href="">Add</a>
        <a class="btn btn-alt" href="">Edit</a>
        <a class="btn btn-alt" href="">Remove</a>
        <a class="btn btn-alt" href="">Search</a>
        <a class="btn btn-alt" href="">Asign</a>
        <a class="btn btn-alt" href="">Suspend</a>
        <a class="btn btn-alt" href="">register</a>

        </section>

        <!-- teasers -->

            <section class="container"> 

               <section>
              {% if not books_list %}
                  <h3>{{ message }}</h3>

                {% else %}
                
                {% for book in books_list %}
   
                <div class="BookDetail">
            <ul>
                <li>
                    <a href="">
                    <h2><a href="{{ book.get_absolute_url }}">{{book.title}}</a></h2>
                    {% if book.descrp %}
                    <h4> About this book :</br>{{ book.descrp }}</h4>
                    {% endif %}
                    <h4> written by :{{ b_auth }}</h4>
                    <h4>Published by :{{ book.publisher }} , on :  {{ book.publicatin_date }}</h4>
                    <h4> viewed : ({{ book.views }}) , liked:({{ number_of_likes }})</h4>

                <!--<h5> written by : {% for writer in book.authors.all %} {{ writer }} {% endfor %}-->
                
                </li>     
                <a href="{% url 'books:conform_delete' book.id %}">Delete</a>
                <a href="{% url 'books:update_book' book.id %}">update</a>
                <a href="{% url 'books:like_this_book' book.id %}">like</a></br>
                ..........................................................................................................

               

            </ul>

        {% endfor %}
        {% endif %}

        
        

        <a href="mailto:maltay@gmail.com?subject=HelloWorld">EmailMe</a>

        <a href="{% url 'books:add_book' %}">add a new book</a>
        </div>
                    <h3>world-class speakers</h3>
                    </a>

                    <p>Every year the world is moving very fast to new consept of development Every year the world is moving very fast to new consept of development</p>
               </section>

                              <section>
                    <a href="">
                    <h5>Schedule</h5>
                    <h3>world-class speakers</h3>
                    </a>

                    <p>Every year the world is moving very fast to new consept of development Every year the world is moving very fast to new consept of development</p>
               </section>

                              <section>
                    <a href="">
                    <h5>venue</h5>
                    <h3>world-class speakers</h3>
                    </a>

                    <p>Every year the world is moving very fast to new consept of development Every year the world is moving very fast to new consept of development</p>
               </section>
           </section>



        

  


        

    <a href="#top">Back</a>
    <footer class="container">
        <small>&copy; FollowUp</small>

                                <nav>
                <a href="">Home</a>
                <a href="">contact us</a>
                <a href="">Promotion</a>
                <a href="">Activty</a>
                <a href="">Donate</a>
            </nav>

    </footer>

    
</body>
</html>

djangoproject1/books/templates/books/login.html
{% load staticfiles %}
<!doctype html>
 
<head>
 
    <!-- Basics -->
     
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
     
    <title>Login</title>
    <link rel = "stylesheet" type="text/css" href = "{% static 'polls/style_for_login.css' %}" />
 
    <!-- 
     
    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/animate.css">
    <link rel="stylesheet" href="css/styles.css">
-->
     
</head>
 
    <!-- Main HTML -->
     
<body>
     
    <!-- Begin Page Content -->
     
    <div id="container">
         
        <form id="login_form" method="post" action=".">
        
          {% csrf_token %}
        
         
            <label for="username">Username:</label>
             
            <input type="text" id="username" name="username">
             
            <label for="password">Password:</label>
             
            <p><a href="#">Forgot your password?</a></p>
             
            <input type="password" id="password" name="password">
             
            <div id="lower">
             
                <input type="checkbox"><label class="check" for="checkbox">Keep me logged in</label>
                 
                <input type="submit" value="Login">
             
            </div><!--/ lower-->
         
        </form>
         
    </div><!--/ container-->
 
     
     
    <!-- End Page Content -->
     
</body>
 
</html>

djangoproject1/books/templates/books/register.html
{% load crispy_forms_tags %}
<!DOCTYPE html>


<html>
    <head>
        <title>Register To Books</title>

        
         <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>

    <body>

        <div class='raw'>
        <div class='col-md-4 col-md-offset-4'>
        <h1>Register here</h1>


        {% if registerd %}

        Rango says : <strog> thanks you for registration </strong>
        <a href="/rango/">Return to the home page</a></br >
        {% else %}

     
        <form id="user_form" method="post" action="/books/register/" enctype="multipart/form-data">

        {% csrf_token %}


        {{ user_form|crispy }}
       

        <input type = "submit" name="submit" value = "Register" />
        </form>

      

                
        {% endif %}
    </div>
</div>


         

    </body>


</html>

djangoproject1/books/templates/books/search_form.html
<html>
<head>
    <title>Search</title>
</head>
<body>


<h4>You cant use more than (10) letters</h4>


{% if errors %}

     <ul>
       {% for error in errors %}

           <li><p style="color: red;">{{ error }}</p></li>
                {% endfor %}
    </ul>
{% endif %}

    <form action="" method="get">
        <input type ="text" name="q">
        <input type="submit" value="search">

    </form>
</body>
</html>

djangoproject1/books/templates/books/search_results.html
<html>
<head>
    <title>Search</title>
</head>
<body>
    <P>You Searched for: <strong>{{query}}</strong></p>

    {%  if books %}
        <p>Found {{books|length}} book{{ books|pluralize }}.</p>
        <ul>

            {% for book in books %}
            <li>{{ book.title}}</li>
            {% endfor %}
        </ul>
        {% else %}
            <p>No books matched your Searched criteria.</p>
        {% endif %}
        </body>
</html>